Brickstorm\CollaborativeTaskManagerBundle\Entity\Task:
  type: entity
  table: bsrm_task
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 30
    description:
      type: text
      nullable: true
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
  oneToOne:
    creator:
      targetEntity: Application\Sonata\UserBundle\Entity\User
      cascade: {  }
      joinColumns:
        creator_id:
          referencedColumnName: id
  manyToOne:
    parliament:
      targetEntity: Brickstorm\ParliamentBundle\Entity\Parliament
      cascade: {  }
      joinColumns:
        parliament_id:
          referencedColumnName: id
      orphanRemoval: true
    areas:
      targetEntity: Brickstorm\ParliamentBundle\Entity\Area
      joinTable:
        name: bsrm_parliament_area
        joinColumns:
          parliament_id:
            referencedColumnName: id
        inverseJoinColumns:
          area_id:
            referencedColumnName: id
  lifecycleCallbacks: {  }